FROM ubuntu:16.04

ENV http_proxy http://proxy.sin.sap.corp:8080
ENV https_proxy http://proxy.sin.sap.corp:8080

RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get -y install \
tmux \
tmuxinator \
emacs \
git \
curl \
python-pip \
python-dev

# For nodejs
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get install -y nodejs

RUN pip install powerline-status psutil

WORKDIR /github
RUN git clone https://github.com/harrifeng/fonts.git /github/fonts
RUN /github/fonts/install.sh
RUN git clone https://github.com/harrifeng/dotfiles.git /github/dotfiles
RUN rm -f /root/.bashrc
RUN ln -s /github/dotfiles/bash/proxy.bashrc /root/.bashrc
RUN ln -s /github/dotfiles/tmux/tmux.conf /root/.tmux.conf
RUN ln -s /github/dotfiles/linux /root/.tumxinator

RUN git clone https://github.com/harrifeng/dotemacsd.git /root/.emacs.d
RUN emacs --batch --eval '(byte-recompile-directory "~/.emacs.d")'
